fluent-bit:

  flush: 1
  logLevel: info
  metricsPort: 2020

  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On

    inputs: |
      [INPUT]
          Name    tail
          Tag     kube.*
          Path    /var/log/containers/*.log
          multiline.parser              docker, cri

    filters: |
      [FILTER]
          Name             kubernetes
          Match            kube.*
          Kube_URL         https://kubernetes.default.svc:443
          Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
          Kube_Tag_Prefix  kube.var.log.containers.
          Merge_Log        On
          Merge_Log_Key    log_processed

    outputs: |
      [OUTPUT]
          name   loki
          match  kube.*
          host   loki-gateway.loki
          port   80