apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: airflow-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.alex.localhost"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: airflow
spec:
  hosts:
    - "airflow.alex.localhost"
  gateways:
    - airflow-gateway
  http:
    - route:
        - destination:
            host: airflow-webserver
            port:
              number: 8080