apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tarantool-app-cartridge
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingressHostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: tarantool-cartridge-role-router
                port:
                  number: 8081