apiVersion: v2
name: promtail
description: A Helm chart for Kubernetes


type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: promtail
    version: 6.16.6
    repository: https://grafana.github.io/helm-charts