apiVersion: v2
name: dognauts-istio
description: A Helm chart for Kubernetes
type: application
version: 0.0.9
appVersion: "1.16.0"
dependencies:
  - name: istiod
    version: 1.16.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: base
    version: 1.16.0
    repository: https://istio-release.storage.googleapis.com/charts
