apiVersion: v2
name: metrics-server
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: metrics-server
    version: 3.11.0
    repository: https://kubernetes-sigs.github.io/metrics-server/