apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kuard-vs
spec:
  hosts:
  - kuard.alex.localhost
  gateways:
  - istio-system/platform-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - kuard.alex.localhost
    route:
    - destination:
        host: kuard
        port:
          number: 80
  http:
  - route:
    - destination:
        host: kuard
        port:
          number: 80