apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-vs
  namespace: keycloak
spec:
  hosts:
  - keycloak.alex.localhost
  gateways:
  - istio-system/platform-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - keycloak.alex.localhost
    route:
    - destination:
        host: keycloak
        port:
          number: 80
  http:
  - route:
    - destination:
        host: keycloak
        port:
          number: 80