apiVersion: v2
name: dex
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: dex
    version: 0.17.1
    repository: https://charts.dexidp.io