dex:
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: keycloak.alex-localhost.ru
        paths:
          - path: /
            pathType: ImplementationSpecific

