apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: artifacts-to-s3
  namespace: argo
spec:
  entrypoint: hello-world-to-file
  templates:
  - name: hello-world-to-file
    container:
      image: busybox
      command: [sh, -c]
      args: ["echo hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: message
        path: /tmp
        s3:
          insecure: true
          endpoint: minio:9000
          bucket: my-bucket
          key: /artifacts/hello_world.txt.tgz
          accessKeySecret:
            name: my-minio-cred
            key: accesskey
          secretKeySecret:
            name: my-minio-cred
            key: secretkey