keycloak:
  global:
    storageClass: "fast.ru-9a"
  resources:
    requests:
#      cpu: 10
      memory: 128Mi
    limits:
#      cpu: 200
      memory: 1280Mi
  extraEnvVars:
  - name: KC_PROXY
    value: "edge"

  auth:
    adminUser: admin
    adminPassword: "admin"

  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: keycloak.alex-localhost.ru
    servicePort: http
    tls: false
    extraTls:
      - hosts:
          - keycloak.alex-localhost.ru
        secretName: alex-localhost-tls
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  keycloakConfigCli:
    enabled: true
    existingConfigmap: "keycloak-realms"