keycloak:
  service:
    type: ClusterIP
    clusterIP: "10.111.40.30"

  extraEnvVars:
  - name: KC_PROXY
    value: "edge"

  auth:
    adminUser: admin
    adminPassword: "admin"

  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: keycloak.alex.localhost
    servicePort: http
    tls: false

  keycloakConfigCli:
    enabled: true
    configuration:
      realm1.json: |
        {
          "realm": "platform",
          "clients": []
        }