kube-prometheus-stack:
  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false
  grafana:
    defaultDashboardsEnabled: false
    adminPassword: admin
#    dashboards: { }
      # default:
      #   custom-dashboard:
      #     file: dashboards/custom-dashboard.json