kube-prometheus-stack:
  alertmanager:
    enabled: false

  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false

  grafana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - grafana.alex.localhost
    env:
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: cBZxLE51D8uIFxHKKhdUecgUoizycxZy
    grafana.ini:
      server:
        root_url: https://grafana.alex.localhost
      auth.generic_oauth:
        enabled: true
        name: Keycloak
        allow_sign_up: true
        scopes: email profile offline_access
        client_id: grafana
        auth_url: http://keycloak.alex.localhost/realms/platform/protocol/openid-connect/auth
        token_url: http://keycloak.keycloak:80/realms/platform/protocol/openid-connect/token
        api_url: http://keycloak.keycloak:80/realms/platform/protocol/openid-connect/userinfo
        role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'

    defaultDashboardsEnabled: false
    adminPassword: admin
    dashboardProviders:
      dashboard-providers.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/services
    dashboards:
      services:
        jupyterhub:
          url: https://raw.githubusercontent.com/iAlexMlops/MLPlatform/main/charts/monitoring/dashboards/jupyterhub.json
          token: ''