victoria-metrics-k8s-stack:
  nameOverride: ""
  fullnameOverride: "vms"

  victoria-metrics-operator:
    enabled: true
    cleanupCRD: false

  vmsingle:
    enabled: false

  vmcluster:
    enabled: true
    spec:
      retentionPeriod: "3"
      replicationFactor: 2
      vmstorage:
        replicaCount: 2
        storageDataPath: "/vm-data"
      vmselect:
        replicaCount: 2
        cacheMountPath: "/select-cache"
      vminsert:
        replicaCount: 2

  alertmanager:
    enabled: true
  defaultRules:
    create: false

  vmagent:
    enabled: true
    spec:
      selectAllByDefault: true
      scrapeInterval: 20s
      inlineScrapeConfig: |
        - job_name: argocd-server-metrics
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              action: keep
              regex: argocd-server-metrics
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              action: keep
              regex: http-metrics
          scheme: http
          metrics_path: /metrics
        
        - job_name: argocd-repo-server-metrics
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              action: keep
              regex: argocd-repo-server-metrics
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              action: keep
              regex: http-metrics
          scheme: http
          metrics_path: /metrics
        
        - job_name: argocd-applicationset-controller-metrics
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              action: keep
              regex: argocd-applicationset-controller-metrics
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              action: keep
              regex: http-metrics
          scheme: http
          metrics_path: /metrics
        
        - job_name: argocd-application-controller-metrics
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              action: keep
              regex: argocd-application-controller-metrics
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              action: keep
              regex: http-metrics
          scheme: http
          metrics_path: /metrics

  kubeScheduler:
    enabled: true

  kubeEtcd:
    enabled: false

  defaultDashboardsEnabled: false
  grafana:
    enabled: true

    grafana.ini:
      server:
        domain: grafana.alex.localhost
        root_url: http://grafana.alex.localhost
        serve_from_sub_path: true
      dashboards:
        default_home_dashboard_path: /var/lib/grafana/dashboards/external/home.json

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - grafana.alex.localhost

    dashboardsConfigMaps:
      external: "grafana-external-dashboards"
      minio: "grafana-minio-dashboards"

    adminUser: admin
    adminPassword: strongpassword

    persistence:
      type: pvc
      enabled: true
      accessModes:
        - ReadWriteMany
      size: 3Gi

    defaultDashboardsTimezone: "Europe/Moscow"
    defaultDatasourceType: "prometheus"

  prometheus-node-exporter:
    enabled: true
    hostRootFsMount:
      enabled: false

  kube-state-metrics:
    enabled: true

  kubeControllerManager:
    enabled: true