kube-prometheus-stack:
  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false

  grafana:
    defaultDashboardsEnabled: false
    adminPassword: admin
    dashboardProviders:
      dashboard-providers.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/services
    dashboards:
      services:
        jupyterhub:
          url: https://raw.githubusercontent.com/iAlexMlops/MLPlatform/main/charts/monitoring/dashboards/jupyterhub.json
          token: ''


loki:
  loki:
    useTestSchema: true
    storage:
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin
      type: s3
      s3:
        endpoint: s3://minio.minio:9000
        secretAccessKey: password
        accessKeyId: admin
#        s3ForcePathStyle: false
#        insecure: false