kube-prometheus-stack:
  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false
  grafana:
    defaultDashboardsEnabled: false
    adminPassword: admin
    dashboards:
     ju:
      custom-dashboard:
        file: dashboards/jupyterhub.json