kube-prometheus-stack:
  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false

  grafana:
    defaultDashboardsEnabled: false
    adminPassword: admin
    dashboardProviders:
      dashboard-providers.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/Services
    dashboards:
      Services:
        jupyterhub:
          url: https://raw.githubusercontent.com/iAlexMlops/MLPlatform/main/charts/monitoring/dashboards/jupyterhub.json
          token: ''