kube-prometheus-stack:
  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false
  grafana:
    defaultDashboardsEnabled: false
    adminPassword: admin
    dashboards:
      jupyterhub:
        local-dashboard:
          url: https://raw.githubusercontent.com/iAlexMlops/MLPlatform/main/charts/monitoring/dashboards/jupyterhub.json
          token: ''