spec:
  source:
    repoURL: https://github.com/iAlexMlops/local-kubernetes-charts.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc

global:
  environment: test
  environmentValues: &environmentValues test.yaml
  argo:
    ingressNginxEnabled: false
    apiVersion: argoproj.io/v1alpha1
    project: default
    namespace: argocd
    syncPolicy:
      selfHeal: false

#ArgoCD nqytE7-kZQnuZD-9

services:

  istio:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: istio
      namespace: istio-system
      chart: charts/istio
    config:

  istio-gateway:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: istio-gateway
      namespace: istio-system
      chart: charts/istio-gateway
    config:

  ingressNginx:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: ingress-nginx
      namespace: ingress-nginx
      chart: charts/ingress-nginx
    config:


  jenkins:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: jenkins
      namespace: jenkins
      chart: charts/jenkins
    config:


  airflow:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: airflow
      namespace: airflow
      chart: charts/airflow
    config:

  mlflow:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: mlflow
      namespace: mlflow
      chart: charts/mlflow
    config:

  tarantool:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: tarantool
      namespace: tarantool
      chart: charts/tarantool
    config:


  metrics-server:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: metrics-server
      namespace: metrics-server
      chart: charts/metrics-server
    config:


  prometheus:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: prometheus
      namespace: prometheus
      chart: charts/prometheus
    config:


  grafana:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: grafana
      namespace: grafana
      chart: charts/grafana
    config:


  minio:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: minio
      namespace: minio
      chart: charts/minio
    config: