spec:
  source:
    repoURL: https://github.com/iAlexMlops/local-kubernetes-charts.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc

global:
  environment: main
  environmentValues: &environmentValues values.yaml
  ingress: istio
  argo:
    apiVersion: argoproj.io/v1alpha1
    project: default
    namespace: argocd
    syncPolicy:
      selfHeal: false


services:
  # Network
  istio:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: istio
      namespace: istio-system
      chart: charts/istio
    config:

  istio-gateway:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: istio-gateway
      namespace: istio-system
      chart: charts/istio-gateway
    config:

  kiali:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: kiali
      namespace: istio-system
      chart: charts/kiali
    config:


  # Monitoring
  metrics-server:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: metrics-server
      namespace: metrics-server
      chart: charts/metrics-server
    config:

  grafana:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: grafana
      namespace: monitoring
      chart: charts/grafana
    config:


  # DevOps
  minio:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: minio
      namespace: minio
      chart: charts/minio
    config:

  cert-manager:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: cert-manager
      namespace: cert-manager
      chart: charts/cert-manager
    config:

  # MLOps

  jupyterhub:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: jupyterhub
      namespace: jupyterhub
      chart: charts/jupyterhub
    config:

  # Common
  kuard:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: kuard
      namespace: kuard
      chart: charts/kuard
    config:

  monitoring:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: monitoring
      namespace: monitoring
      chart: charts/monitoring
    config:

  kiali-operator:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: kiali
      namespace: kiali-operator
      chart: charts/kiali
    config: