spec:
  source:
    repoURL: https://github.com/iAlexMlops/local-kubernetes-charts.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc

global:
  environment: main
  environmentValues: &environmentValues values.yaml
  ingress: nginx
  argo:
    apiVersion: argoproj.io/v1alpha1
    project: default
    namespace: argocd
    syncPolicy:
      selfHeal: false


services:
  # Network
  ingressNginx:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: ingress-nginx
      namespace: ingress-nginx
      chart: charts/ingress-nginx
    config:

  # Monitoring
  metrics-server:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: metrics-server
      namespace: metrics-server
      chart: charts/metrics-server
    config:

  monitoring:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: monitoring
      namespace: monitoring
      chart: charts/monitoring
    config:

  # MLOps
  jupyterhub:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: jupyterhub
      namespace: jupyterhub
      chart: charts/jupyterhub
    config:

  dex:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: dex
      namespace: dex
      chart: charts/dex
    config:

  argo-workflows:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: argo-workflows
      namespace: argo
      chart: charts/argo-workflows
    config:

  # Others
  minio-operator:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: minio-operator
      namespace: minio-operator
      chart: charts/minio-operator
    config:

  minio-tenant:
    enable: true
    valueFile: *environmentValues
    argoApplication:
      name: minio-tenant
      namespace: minio-tenant
      chart: charts/minio-tenant
    config:
