spec:
  source:
    repoURL: https://github.com/iAlexMlops/local-kubernetes-charts.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc

global:
  environment: main
  environmentValues: &environmentValues values.yaml
  ingress: istio
  argo:
    apiVersion: argoproj.io/v1alpha1
    project: default
    namespace: argocd
    syncPolicy:
      selfHeal: false


services:
  # Network
  istio:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: istio
      namespace: istio-system
      chart: charts/istio
    config:

  istio-gateway:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: istio-gateway
      namespace: istio-system
      chart: charts/istio-gateway
    config:

  kiali:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: kiali
      namespace: istio-system
      chart: charts/kiali
    config:


  # Monitoring
  metrics-server:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: metrics-server
      namespace: metrics-server
      chart: charts/metrics-server
    config:

  grafana:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: grafana
      namespace: grafana
      chart: charts/grafana
    config:


  # DevOps
  jenkins:
    enable: false
    istioEnabled: true
    valueFile: *environmentValues
    argoApplication:
      name: jenkins
      namespace: jenkins
      chart: charts/jenkins
    config:

  mlflow:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: mlflow
      namespace: mlflow
      chart: charts/mlflow
    config:

  minio:
    enable: false
    valueFile: *environmentValues
    argoApplication:
      name: minio
      namespace: minio
      chart: charts/minio
    config:


  # Common
