minio:
  ingress:
    enabled: false

  auth:
    rootUser: admin
    rootPassword: password

  provisioning:
    buckets:
    - name: loki
      quota:
        type: clear
        size: 3GiB
      tags:
        app: loki