loki:

  loki:
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
        - from: 2024-04-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    ingester:
      chunk_encoding: snappy
    tracing:
      enabled: true
    querier:
      max_concurrent: 2
    storage:
      type: filesystem
    auth_enabled: false

  memberlist:
    service:
      publishNotReadyAddresses: true

  deploymentMode: SingleBinary
  singleBinary:
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 800Mi
      requests:
        cpu: 50m
        memory: 200Mi
    extraEnv:
      - name: GOMEMLIMIT
        value: 750MiB

  chunksCache:
    writebackSizeLimit: 10MB
    resources:
      limits:
        cpu: 200m
        memory: 800Mi
      requests:
        cpu: 50m
        memory: 200Mi

  minio:
    enabled: false

  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0
