tenant:
  secrets:
    name: minio-env-configuration
    accessKey: minio
    secretKey: minio123

  tenant:
    name: minio

    configuration:
      name: minio-env-configuration
    pools:
      - servers: 2
        name: pool-0
        volumesPerServer: 2
        size: 1Gi
    mountPath: /export
    subPath: /data

    metrics:
      enabled: true
      port: 9000
      protocol: http

    certificate:
      requestAutoCert: true

    features:
      bucketDNS: false
      enableSFTP: false

    buckets:
      - name: models

    env:
      MINIO_PROMETHEUS_AUTH_TYPE: public

    prometheusOperator: false

  ingress:
    api:
      enabled: false
    console:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/rewrite-target: /
      ingressClassName: "nginx"
      tls:
        - secretName: minio-tls
          hosts:
            - minio.alex.localhost
      host: minio.alex.localhost
