apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mlflow-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.alex.localhost"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mlflow
spec:
  hosts:
    - "mlflow.alex.localhost"
  gateways:
    - mlflow-gateway
  http:
    - route:
        - destination:
            host: mlflow
            port:
              number: 5000