apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mlflow
spec:
  hosts:
    - "mlflow.alex.localhost"
  gateways:
    - app-gateway
  http:
    - route:
        - destination:
            host: mlflow
            port:
              number: 5000