apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: request-authentication
spec:
  jwtRules:
    - forwardOriginalToken: true
      issuer: "https://dev-kzyb4oxa1setftab.us.auth0.com/"
      jwksUri: "https://dev-kzyb4oxa1setftab.us.auth0.com/.well-known/jwks.json"
  selector:
    matchLabels:
      type-app: mlflow