apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: auth-policy
spec:
  targets:
    - name: sa-web-app
    - name: sa-feedback
  origins:
    - jwt:
        issuer: "https://dev-kzyb4oxa1setftab.us.auth0.com/"
        jwksUri: "https://dev-kzyb4oxa1setftab.us.auth0.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN