apiVersion: v2
name: argocd
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: argo-cd
    version: 5.45.0
    repository: https://argoproj.github.io/argo-helm