argo-cd:
  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: "argocd.alex-localhost.ru"
      path: /
      pathType: Prefix
      tls: false
      extraTls:
        - hosts:
            - argocd.alex-localhost.ru
          secretName: platform-certificate

  crds:
    install: true
  configs:
    cm:
      url: https://argocd.alex-localhost.ru
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.alex-localhost.ru/realms/master
        clientID: argocd
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
    params:
      server.insecure: true
      dexserver.disable.tls: true
      server.dex.server.plaintext: true
    repositories:
      main-platform-repo:
        url: https://github.com/iAlexMlops/MLPlatform.git
        name: Main platform repository
        type: git
    secret:
      argocdServerAdminPassword: "$2a$10$Vez/QiLsyjujyRQ5Og580.U2Ihh713NZMbNFyYB9FnRTIpM8WNmue"
      extra:
        oidc.keycloak.clientSecret: "cR4Agamttc7L6n5HZ1bvii166IIR0ZCX"