argo-cd:
  dex:
    enabled: true

  controller:
    metrics:
      enabled: true

  redis:
    metrics:
      enabled: false

  repoServer:
    metrics:
      enabled: true

  applicationSet:
    metrics:
      enabled: true


  server:
    metrics:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: "argocd.alex.localhost"
      path: /
      pathType: Prefix


  configs:
    params:
      server.insecure: true
      dexserver.disable.tls: true
      server.dex.server.plaintext: true
    repositories:
      main-platform-repo:
        url: https://github.com/iAlexMlops/MLPlatform.git
        name: Main platform repository
        type: git
    secret:
      argocdServerAdminPassword: "$2a$10$Vez/QiLsyjujyRQ5Og580.U2Ihh713NZMbNFyYB9FnRTIpM8WNmue"
      extra:
        oidc.keycloak.clientSecret: "gOwjpnw3vtBmyYWJra0rngUGblVzUqk4"

  crds:
    install: true