{{- range $serviceName, $serviceConfig := .Values.services }}
{{- if $serviceConfig.enable -}}
---
# Application for {{ $serviceName }}
apiVersion: {{ $.Values.global.argo.apiVersion }}
kind: Application
metadata:
  name: {{ $serviceConfig.argoApplication.name }}
  namespace: {{ $.Values.global.argo.namespace }}
spec:
  project: {{ $.Values.global.argo.project }}
  source:
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    path: {{ $serviceConfig.argoApplication.chart }}
    helm:
      valueFiles:
        -  {{ $serviceConfig.valueFile }}
      parameters:
{{- with $serviceConfig -}}
{{- if or .config }}
{{- range $key, $value := .config }}
        - name: {{ $key | squote }}
          value: {{ $value | squote }}
{{- end }}
{{- end }}
{{- end }}
  destination:
    namespace: {{ $serviceConfig.argoApplication.namespace }}
    server: {{ $.Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: {{ $.Values.global.argo.syncPolicy.selfHeal }}
    syncOptions:
      - CreateNamespace=true
{{ end -}}
{{ end -}}
