{{- if .Values.jenkins.enable -}}
{{- with .Values.jenkins -}}
apiVersion: {{ $.Values.global.argo.apiVersion }}
kind: Application
metadata:
  name: {{ .argoApplication.name }}
  namespace: {{ $.Values.global.argo.namespace }}
spec:
  project: {{ $.Values.global.argo.project }}
  source:
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    path: {{ .argoApplication.chart }}
    helm:
      valueFiles:
      -  {{ $.Values.jenkins.valueFile }}
      parameters:
      {{- with $.Values.jenkins -}}
      {{- if or .config }}
      {{- range $key, $value := .config }}
        - name: {{ $key | squote }}
          value: {{ $value | squote }}
      {{- end }}
      {{- end }}
      {{- end }}
  destination:
    namespace: {{ $.Values.jenkins.argoApplication.namespace }}
    server: {{ $.Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: {{ $.Values.global.argo.syncPolicy.selfHeal }}
    syncOptions:
      - CreateNamespace=true
{{- end -}}
{{- end -}}