apiVersion: v1
kind: Secret
metadata:
  name: platform-certificate
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/cert.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/key.key" | b64enc }}
