apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd
spec:
  hosts:
    - "argocd.alex.localhost"
  gateways:
    - platform-gateway
  http:
    - match:
        - port: 443
      route:
        - destination:
            host: argocd-server
            port:
              number: 80