apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system
spec:
  hosts:
  - kiali.alex.localhost
  gateways:
  - istio-system/platform-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - kiali.alex.localhost
    route:
    - destination:
        host: kiali
        port:
          number: 20001
  http:
  - route:
    - destination:
        host: kiali
        port:
          number: 20001