grafana:
  adminUser: admin
  adminPassword: admin

  ingress:
    enabled: false
    ingressClassName: nginx
    pathType: ImplementationSpecific
    hosts:
      - grafana.alex.localhost

istioRef:
  grafana:
    gateways: "istio-system/alexgateway"
    hosts: "grafana.alex.localhost"