grafana:
  adminUser: admin
  adminPassword: admin

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: istio
    path: /
    pathType: Prefix
    hosts:
      - grafana.alex.localhost