airflow:
  defaultAirflowRepository: apache/airflow
  airflowVersion: "2.7.0"

  ingress:
    enabled: false
    web:
      enabled: true
      pathType: "ImplementationSpecific"
      host: "airflow.alex.localhost"
      ingressClassName: nginx
      hosts:
        - name: "airflow.alex.localhost"
          tls:
            enabled: true
            secretName: "airflow.alex.localhost"

  webserver:
    defaultUser:
      enabled: true

      role: Admin
      username: admin
      password: admin

      email: a.egorov@ktsstudio.ru
      firstName: admin
      lastName: user
