airflow:
  defaultAirflowRepository: apache/airflow
  airflowVersion: "2.7.0"


  images:
    airflow:
      repository: ~
      tag: ~
      pullPolicy: Always


  ingress:
    enabled: false
    web:
      enabled: true
      pathType: "ImplementationSpecific"
      host: "airflow.alex.localhost"
      ingressClassName: nginx
      hosts:
        - name: "airflow.alex.localhost"
          tls:
            enabled: true
            secretName: "airflow.alex.localhost"


  executor: "KubernetesExecutor"


  extraEnv: |
    - name: AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE
      value: 'Europe/Moscow'
    - name: TZ
      value: 'Europe/Moscow'
    - name: FS_ETL_OMIT_VERSION
      value: '1'
    - name: HADOOP_CONF_DIR
      value: '/opt/hadoop'


  data:
    metadataConnection:
      user: postgres
      pass: postgres
      protocol: postgresql
      host: ~
      port: 5432
      db: airflow
      sslmode: disable

  webserver:
    defaultUser:
      enabled: true

      role: Admin
      username: admin
      password: admin

      email: a.egorov@ktsstudio.ru
      firstName: admin
      lastName: user

  kerberos:
    enabled: false


  workers:
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: "100%"
        maxUnavailable: "50%"
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: hostpath
      fixPermissions: false
    logGroomerSidecar:
      command: ~
      args: ["bash", "/clean-logs"]
      retentionDays: 30


  scheduler:
    logGroomerSidecar:
      enabled: true
      command: ~
      args: ["bash", "/clean-logs"]
      retentionDays: 30


  createUserJob:
    useHelmHooks: false


  migrateDatabaseJob:
    useHelmHooks: false


  statsd:
    enabled: false


  redis:
    enabled: true
    persistence:
      enabled: true
      storageClassName: hostpath
      size: 1Gi


  postgresql:
    enabled: true
    auth:
      username: postgres
      password: postgres
    postgresqlDatabase: airflow
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: hostpath



  dags:
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: hostpath
      accessMode: ReadWriteOnce
      existingClaim:
      subPath: ~


  logs:
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: hostpath
