apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: first-app
spec:
  hosts:
    - first-app
  http:
    - route:
        - destination:
            host: first-app
            subset: v1
          weight: 90
        - destination:
            host: first-app
            subset: v2
          weight: 10