argo-workflows:
  crds:
    install: true
  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - awf.alex.localhost
      paths:
        - /
      pathType: Prefix

    authMode: server