apiVersion: v2
name: kiali
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: kiali-server
    version: 1.73.0
    repository: https://kiali.org/helm-charts