kiali-operator:
  cr:
    create: true
    name: kiali
    namespace: istio-system
    spec:
      auth:
        strategy: "anonymous"
      external_services:
        custom_dashboards:
          enabled: true
        grafana:
          auth:
            insecure_skip_verify: true
            password: 'prom-operator'
            username: 'admin'
          dashboards:
            - name: Istio Service Dashboard
              variables:
                namespace: var-namespace
                service: var-service
            - name: Istio Workload Dashboard
              variables:
                namespace: var-namespace
                workload: var-workload
            - name: Istio Mesh Dashboard
            - name: Istio Control Plane Dashboard
            - name: Istio Performance Dashboard
            - name: Istio Wasm Extension Dashboard
          enabled: true
          in_cluster_url: http://monitoring-grafana.monitoring:80
        prometheus:
          url: http://prometheus-operated.monitoring:9090
        istio:
          component_status:
            components:
              - app_label: istiod
                is_core: true
                is_proxy: false
                namespace: ''
              # TODO: istio-ingressgateway not found
              - app_label: istio-ingressgateway
                is_core: true
                is_proxy: true
                namespace: ''
              - app_label: istio-egressgateway
                is_core: false
                is_proxy: true
                namespace: ''
            enabled: false
        tracing:
          enabled: false
