ingressHostname: tarantool.alex.localhost
ingressPort: &ingressPort 8081
tarantoolPort: &tarantoolPort 3301


tarantool-operator:
  image:
    repository: tarantool/tarantool-operator
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1


cartridge:
  tarantool:
    image:
      repository: ialexmlops/cartridge
      tag: test
      pullPolicy: IfNotPresent


    runDir: /var/run/tarantool
    workDir: /var/lib/tarantool

    securityContext:
      fsGroup: 1200
      allowPrivilegeEscalation: true


    auth:
      user: "admin"
      password: "admin"


    roles:
      - name: storage
        replicasets: 2
        replicas: 2
        vshard:
          weight: 100
          roles:
            - app.roles.storage
        persistence:
          enabled: true
          spec:
            resources:
              requests:
                storage: 2Gi


      - name: router
        replicasets: 2
        replicas: 1
        service:
          type: ClusterIP
          ports:
            http: *ingressPort
            tarantool: *tarantoolPort
        vshard:
          allRw: true
          weight: 1
          roles:
            - app.roles.router
        persistence:
          enabled: true
          spec:
            resources:
              requests:
                storage: 1Gi