apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-dind
  name: docker-dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-dind
  template:
    metadata:
      labels:
        app: docker-dind
    spec:
{{/*      initContainers:*/}}
{{/*        - name: volume-mount-hack*/}}
{{/*          image: busybox*/}}
{{/*          command: [ "sh", "-c", "chown -R 1000:1000 /home/rootless/.local/share/docker" ]*/}}
{{/*          volumeMounts:*/}}
{{/*            - name: docker-dind-data-vol*/}}
{{/*              mountPath: /home/rootless/.local/share/docker*/}}
      containers:
        - image: docker:24.0.5-dind
          name: docker-dind
          env:
            - name: DOCKER_HOST
              value: tcp://0.0.0.0:2375
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - name: docker-dind-data-vol
              mountPath: /var/lib/docker
            - name: docker-dind-daemon-config
              mountPath: /etc/docker
          ports:
            - name: daemon-port
              containerPort: 2375
              protocol: TCP
          securityContext:
            privileged: true
      volumes:
        - name: docker-dind-daemon-config
          configMap:
            name: docker-dind-daemon-config
        - name: docker-dind-data-vol
          persistentVolumeClaim:
            claimName: docker-dind-data